apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-backend-deployment
spec:
  replicas: 1  # Adjust as necessary
  selector:
    matchLabels:
      app: hospital-backend
  template:
    metadata:
      labels:
        app: hospital-backend
    spec:
      containers:
      - name: Hospital-backend-container
        image: ujas/Hospital-app-backend:15  # Replace this with your Docker image name
        ports:
        - containerPort: 8080  # Replace with your app's port if necessary
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: hospital-backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: hospital-backend-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: hospital-backend-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hospital-backend-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hospital-backend-secret
              key: DB_PASSWORD

