apiVersion: v1
kind: Secret
metadata:
  name: hospital-backend-secret
type: Opaque
data:
  DB_USERNAME: ZGlnaXRhbGFkbWlu
  DB_PASSWORD: c3VwcG9ydEAxMjNBQkM=


## echo -n "root" | base64
## echo -n "password123ABC" | base64
