# apiVersion: v1
# kind: Service
# metadata:
#   name: hospital-backend-service
# spec:
#   selector:
#     app: hospital-backend-service
#   ports:
#     - protocol: TCP
#       port: 8080   # The service port exposed internally
#       targetPort: 8080  # Container port where your Spring Boot app listens
#   type: ClusterIP  # Change LoadBalancer to ClusterIP

#--- 
apiVersion: v1
kind: Service
metadata:
  name: hospital-backend-service
  labels:
    app: hospital-backend
spec:
  selector:
    app: hospital-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
